Exam
tautvydasLiekis/code pull request #1
Opened 2020-09-28 14:29 UTC by tautvydasLiekis

Spejau padaryti tik prisijungimo patikrinima ir irasima i duomenu baze. Pradejau strikti ant "JOIN" (INNER, LEFT), todel nespejau padaryti kitu punktu. JDBC jungtis ir susijes kodas ir kaip ji panaudoti yra aisku padarytose ir nepadarytose uzduotyse. Tiktai noretusi suzinoti kaip sioje uzduotyje buvo galima padaryti lentele (dariau forward-engineering is MySQL modelio) taip kad "JOIN" grazintu rezultata.

2020-09-28 20:30 UTC, pavelvrublevskij reviewed
Netraukiam *.class, .idea, target i versijavima.

2020-09-28 20:30 UTC, pavelvrublevskij commented on .idea/compiler.xml
> +</project>
itraukiam i .gitignore aplana .idea

2020-09-28 20:30 UTC, pavelvrublevskij commented on .idea/dataSources/d9a50dc1-0baf-42ea-9176-bc6ede2af609/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
> +!<md> [null, 0, null, null, -2147483648, -2147483648]
Nereikia sito versijuoti

2020-09-28 20:30 UTC, pavelvrublevskij commented on src/main/java/Main.java
> +
Taip, labai truksta funkcionalumo, manau rasi laiko padarti koki viena kita punkta ;)

2020-09-28 20:34 UTC, pavelvrublevskij requested changes
Turi idomu rasymo syliu. Is kodo matosi kad stengeisi daryti teisingai ir matosi kad galetum padaryti uzdavini, nes ... tiesiog matosi kad gali daugiau. Zinoma yra niuansu bet jas noreciau aptarti (pateikti feedback) kai dar truputi skirsi laiko kokiam 1-2 funkcionalumi.
Bendrai uzskaitau.

2020-09-28 20:35 UTC, pavelvrublevskij commented
Nepamirsk ir Elvina prideti

2020-09-29 14:57 UTC, tautvydasLiekis commented
Aciu uz pastabas! per sia savaite atliksiu daugiau ir pataisysiu pagal pastabas

2020-10-06 06:33 UTC, Elvinasl approved these changes

2020-10-06 06:33 UTC, Elvinasl commented on src/main/java/Main.java
> +    public static void printMenuAfterLogin() {
Stenkimes vengti statiniu metodu. Galima klase sukurti ir juos iskviesti :)

2020-10-06 06:33 UTC, Elvinasl commented on src/main/java/Main.java
> +                    System.out.println("Wrong input!");
Pagalvok apie message string'us galbut galima juos irgi vienoj klasej turet apsirasius? O galbut .properties faile?

2020-10-06 06:33 UTC, Elvinasl commented on src/main/java/model/UserInfo.java
> +
Kodel tiek daug tarpu palieki?

2021-12-21 20:48 UTC, closed without merging